### PR TITLE
Allow to store Basic Auth passwords hashed in config files

### PR DESCRIPTION
**Pull request by ravenclaw900**
Allows to store passwords used for HTTP Basic Authentication (and dashboard and admin UI) hashed using BCrypt.

### CODE REVIEW

**Comment by ravenclaw900** [comment]
bump

**Comment by ravenclaw900** [comment]
bump

**Comment by ravenclaw900** [comment]
bump

**Comment by ravenclaw900** [comment]
bump

**Comment by ravenclaw900** [comment]
bump

**Comment by ravenclaw900** [comment]
bump

**Comment by fatedier** [comment]
Can you open an issue to describe more about your feature?

**Comment by ravenclaw900** [comment]
bump

**Comment by ravenclaw900** [comment]
Bump

**Comment by ravenclaw900** [comment]
bump

**Comment by ravenclaw900** [comment]
Sorry for the long wait, and all of the `bump` messages. Should work with the dashboard, admin UI, and `http` type proxies now. Quite a few functions, like `HTTPBasicAuth` and `HTTPAuthWraper.ServeHTTP` don't seem to do much, so I didn't add authentication there. Also, not sure if the `RouteConfig` is the best place to store the `Hashed` variable, but I didn't see anything else.

**Comment by fatedier** [comment]
You don't follow my solution in this comment https://github.com/fatedier/frp/issues/2747#issuecomment-1008950564 .

We need to consider the generality of the feature, instead of constantly adding new parameters.

By the way, we are planning to work on [frp v2](https://github.com/fatedier/frp#development-status). I  prefer not to keep maintaining these features in the current version.

**Comment by ravenclaw900** [comment]
In that case, I'd be happy to close it and maybe try reimplementing in v2 later.

**Pull request closed without merging**
