### PR TITLE
Changed LoginFailExit to LoginFailRetry

### PR DESCRIPTION
**Pull request by Mewster**
When client attempts a connection to the server, attempts a certain amount of times before exiting.

### CODE REVIEW

**Comment by Mewster** [comment]
I'm preparing another pull request to add backward compatibility with login_fail_exit

**Comment by fatedier** [comment]
See https://github.com/fatedier/frp/issues/1029.

It's a deprecated feature and will be removed in the future. Using scripts or other systemctl tools to do the same thing.

**Comment by Mewster** [comment]
> See #1029.
> 
> It's a deprecated feature and will be removed in the future. Using scripts or other systemctl tools to do the same thing.

If this will be removed in the future, how can one configure a similar setup without using external scripts? Is there a reason why it's going to be deprecated?

**Comment by fatedier** [comment]
It's nothing about frp. We should focus on the primary thing.

Do not let one program do all things.

**Comment by Mewster** [comment]
> It's nothing about frp. We should focus on the primary thing.
> Do not let one program do all things.

I'm sorry, but I can't understand why the client shouldn't be configurable to manage specific login use-case out of the box without resorting to external system tools. I know it's not a primary functionality, but I wouldn't discard this feature either without a reason...

**Comment by fatedier** [comment]
It's not a feature for one specified program.
Systemd and other similar programs may be the best choice. I don't want to add features like this to make this project complicated.

Provide a script to do things like this is another choice.

**Comment by Mewster** [comment]
> It's not a feature for one specified program.
> Systemd and other similar programs may be the best choice. I don't want to add features like this to make this project complicated.
> 
> Provide a script to do things like this is another choice.

Can systemd or a script know that there have been a failed login, and setup a login-retry rule?

**Comment by fatedier** [comment]
If login failed, it will exit with a none zero code.

**Comment by Mewster** [comment]
> If login failed, it will exit with a none zero code.

Understood, thanks.

**Pull request closed without merging**
