### PR TITLE
chore: use scratch as docker base image to shrink image size

### PR DESCRIPTION
**Pull request by skiloop**
Docker images can be shrink to very small size with scratch for go applications.

https://blog.codeship.com/building-minimal-docker-containers-for-go-applications/

### CODE REVIEW

**Comment by fatedier** [comment]
There is already a `Dockerfile_multiple_build` file in root dir and i may remove docker support in this project in future.

**Comment by skiloop** [comment]
> There is already a `Dockerfile_multiple_build` file in root dir and i may remove docker support in this project in future.

Docker support is quit useful in many case, I think is not a good idea to remove it. 
By the way, scratch is much smaller than alpine image too, compressed image can be as small as 9m.

**Comment by fatedier** [comment]
You can put it in other repos about how to use frp in docker.
This repo will only reserve codes since it's not good maintained here.

**Comment by Jefffish09** [comment]
@fatedier sorry that I cannot find the file `Dockerfile_multiple_build` now in root dir of the repo.

**Pull request closed without merging**
