### PR TITLE
udp: Add an Unlock before a continue, to fix a double lock bug

### PR DESCRIPTION
**Pull request by lzhfromustc**
***Description***
A mutex `mu` is locked at line 115 of [udp.go](https://github.com/fatedier/frp/blob/master/models/proto/udp/udp.go#L115), and unlocked at line 124. However, there is a `continue` at line 120 if `err != nil`, and there is no unlock before this `continue`. So if the `continue` is executed, there will be a double lock bug.

***How it is fixed***
Add an `mu.Unlock()` before the continue.

### CODE REVIEW

**Comment by fatedier** [comment]
Can you send this PR to dev branch?

**Comment by lzhfromustc** [comment]
Sure, I changed it to fatedier:dev

**Comment by fatedier** [comment]
You'd better checkout dev branch and cherry-pick this commit, then `push -f` to not keep commit history from master branch .

**Comment by lzhfromustc** [comment]
I see the point. However, github doesn't allow me to change the `lzhfromustc:udp_mis_unlock` in this PR into `lzhfromustc:dev`. If I just pull from `fatedier:dev` into `lzhfromustc:udp_mis_unlock`, I got lots of commits.
How about I close this PR and open another one based on `fatedier:dev`?

**Comment by fatedier** [comment]
`git push -f` can force update `lzhfromustc:udp_mis_unlock`.

**Comment by lzhfromustc** [comment]
Sorry for the trouble. I used `git pull origin dev` and `git push -f`, but now I have a lot of commits, and I can't simply rebase them. So maybe it is more clean for me to just close this PR?

**Comment by fatedier** [comment]
OK. You can open a new PR.

**Pull request closed without merging**
