### PR TITLE
Update docker image build file

### PR DESCRIPTION
**Pull request by BecodReyes**
https://github.com/fatedier/frp/issues/2889

应该没什么问题

alpine支持的架构都支持了
`linux/386` `linux/amd64` `linux/arm/v6` `linux/arm/v7` `linux/arm64/v8` `linux/ppc64le` `linux/s390x`

需要环境变量：
`DOCKERHUB_USERNAME` `DOCKERHUB_PASSWORD`

上传了一份编译成功的frpc
[dockerhub](https://hub.docker.com/r/becod/frpc)
[ghcr.io](https://ghcr.io/becodreyes/frpc)

### CODE REVIEW

**Comment by fatedier** [comment]
You'd better minimize your changes. Don't edit code that doesn't matter.

**Comment by BecodReyes** [comment]
> You'd better minimize your changes. Don't edit code that doesn't matter.

Yep, modified.

**Comment by freeman-x** [comment]
I'm new frp user, find your docker fatedier/frps at dockerhub, but don't know how to change the frps.ini file.

**Comment by jinmiaoluo** [comment]
> I'm new frp user, find your docker fatedier/frps at dockerhub, but don't know how to change the frps.ini file.

suppose u are using the latest image.

`docker  run  -v `readlink -f frps.ini`:/etc/frps.ini fatedier/frps:v0.42.0 -c /etc/frps.ini`

**Pull request merged**
