### PR TITLE
vhost: set DisableKeepAlives = false and fix websocket not work

### PR DESCRIPTION
**Pull request by fatedier**

### CODE REVIEW

**Comment by gao270615179** [comment]
It works for websocket!

**Review by yuyulei — APPROVED** [review]

**Comment by yuyulei** [comment]
LGTM

**Comment by michalfapso** [comment]
Thanks a lot! I was struggling with my websockets frp tunnel and was so happy to find out that you've already fixed the issue and all I have to do is to update my frps version :)

**Comment by NullBirdie** [comment]
需要有什么特殊的配置嘛？我只设置80、443的custom_domains就行还是需要给websocket单独设置什么？

**Pull request merged**
