### PR TITLE
Add close issue bot

### PR DESCRIPTION
**Pull request by BecodReyes**
Automatically close the issue that does not conform to the specification

Time is precious. We can't waste time on non conforming issues

Tips: After processing the pull request, you need to install the [close-issue-app](https://github.com/apps/close-issue-app) to make it work properly

### CODE REVIEW

**Comment by fatedier** [comment]
Can we use github actions instead of an app?

**Comment by BecodReyes** [comment]
It can be achieved, but it may take a long time to wait

**Comment by fatedier** [comment]
No problem and thanks for you contribution. I prefer use github actions so all similar configures can be modified in this repo files, no need to find how to config it in other place.

**Comment by BecodReyes** [comment]
The configuration file for this github app is also stored in this repo file.

You configure it just as you configure github action.

I've configured and tested it, and it will work after merging.

**Comment by fatedier** [comment]
The configures include if we enable this feature.

**Comment by BecodReyes** [comment]
What? I mean I've configured and tested it, out of the box.

**Pull request closed without merging**
