### PR TITLE
feat: support add additional params for OIDC

### PR DESCRIPTION
**Pull request by bingtianbaihua**
https://github.com/fatedier/frp/pull/2802
https://github.com/fatedier/frp/pull/1714

### CODE REVIEW

**Comment by bingtianbaihua** [comment]
Hello @addisonj  I saw your PR https://github.com/fatedier/frp/pull/2802 .

I think the auth0 is using not-standard OAuth2.0. 

https://datatracker.ietf.org/doc/html/rfc6749 
https://community.auth0.com/t/client-credentials-with-postman/34282/5

I warry about if there are auth1, auth2 companies which also need audience parameters but its value is not equal "cfg.OidcAudience" but "foobar".  So I think hard code in frp is not suitable.  I make it configurable.

And also, I register a auth0 service account. In my PR, I test as follow.

image

image


```
frps.ini

authentication_method = oidc
oidc_issuer = https://dev-xxx.us.auth0.com/
oidc_audience = https://dev-xxx.us.auth0.com/api/v2/

frpc.ini
authentication_method = oidc
oidc_client_id = pExxxKqoxxxBH
oidc_client_secret = F3492WS5pxxxxx8OG83DWxxxxx5nP3Oe-Lxcaoxxxx
oidc_audience = ""
oidc_token_endpoint_url = https://dev-xxx.us.auth0.com/oauth/token
oidc_additional_audience = https://dev-xxx.us.auth0.com/api/v2/   // It will be set by frp  audience=<value> 

```

It pass test in auth0 service. 

---

@fatedier @GuyLewin  WDYT ?

**Comment by StarryVoid** [comment]
Hi
I just tested the linkage between auth0 and frp_oicp, and it is very similar to the configuration you used, but an error is reported

The Log is
`2022/03/02 13:43:33 [W] [service.go:105] login to server failed: couldn't generate OIDC token for login: oauth2: cannot fetch token: 403 Forbidden`
`Response: {"error":"access_denied","error_description":"No audience parameter was provided, and no default audience has been configured"}`
`couldn't generate OIDC token for login: oauth2: cannot fetch token: 403 Forbidden`
`Response: {"error":"access_denied","error_description":"No audience parameter was provided, and no default audience has been configured"}`

The Config is
```
frps.ini
authentication_method = oidc
oidc_issuer = https://dev-xxx.jp.auth0.com/
oidc_audience = https://dev-xxx.jp.auth0.com/api/v2/

frpc.ini
authentication_method = oidc
oidc_client_id = "IDXXXXXXXX"
oidc_client_secret = "SXXXXXXXX"
#oidc_audience = ""
oidc_audience = "https://dev-xxx.jp.auth0.com/api/v2/"
oidc_token_endpoint_url = "https://dev-xxx.jp.auth0.com/oauth/token/"
oidc_additional_audience = "https://dev-xxx.jp.auth0.com/api/v2/"

```
The Auth0 Config
```
User -> Applications -> Applications -> Create Applications -> Name=Demo-FRP & Machine to Machine Applications -> Select "Auth0 Management API" & Permissions "ALL" -> Finish
User -> Applications -> APIs -> Auth0 Management API Settings -> Test -> Select "Demo-FRP" -> Select "Curl" -> Copy "URL" "client_id" "client_secret" "audience"
```
Auth0  &&  FRP_OIDC
```
"client_id" ==> oidc_client_id
"client_secret" ==> oidc_client_secret
"audience" ==> oidc_audience
"System API Identifier" ==> oidc_audience & oidc_additional_audience
"Curl url" ==> oidc_token_endpoint_url
```

> Hello @addisonj I saw your PR #2802 .
> 
> I think the auth0 is using not-standard OAuth2.0.
> 
> https://datatracker.ietf.org/doc/html/rfc6749 https://community.auth0.com/t/client-credentials-with-postman/34282/5
> 
> I warry about if there are auth1, auth2 companies which also need audience parameters but its value is not equal "cfg.OidcAudience" but "foobar". So I think hard code in frp is not suitable. I make it configurable.
> 
> And also, I register a auth0 service account. In my PR, I test as follow.

**Comment by addisonj** [comment]
@bingtianbaihua I think this seems reasonable. I was thinking of something like this as well might be preferable. LGTM!

**Comment by bingtianbaihua** [comment]
> @bingtianbaihua I think this seems reasonable. I was thinking of something like this as well might be preferable. LGTM!

@addisonj  OK，I will refine my code and merge it these days.  By the way you can close your PR.

**Review by fatedier — APPROVED** [review]

**Pull request merged**
